Add the `event` doc
redis/node-redis pull request #1745
Opened 2021-11-29 14:17 UTC by AnnAngela

Please help me to improve the writing, my English is so bad :(

### Description

> Add the `event` doc

---

### Checklist

- [ ] Does `npm test` pass with this change (including linting)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

The PR only changes a doc.

Please help me to improve the writing, my English is so bad :(

2021-11-29 19:50 UTC, guyroyse commented
Thanks for the contribution, @AnnAngela. Very helpful. I'd like to edit it a bit for grammar and spelling. Can you grant me access to do so? Thanks!

2021-11-30 00:04 UTC, AnnAngela commented
Yes, I am very grateful for your willingness to help me!

2021-11-30 17:45 UTC, guyroyse requested changes

2021-11-30 17:45 UTC, guyroyse commented on README.md
> +Node Redis client class extends Node.js's `EventEmitter` class, and the client emits an event each time the network status changes:
The Node Redis client class is an `EventEmitter` and it emits an event each time the network status changes:

2021-11-30 17:45 UTC, guyroyse commented on README.md
> +| Event name   | Scenes | Parameters |
Can we clean up the table format here to be a bit tidier?

2021-11-30 17:45 UTC, guyroyse commented on README.md
> +| Event name   | Scenes | Parameters |
I like to use this site: http://markdowntable.com/

2021-11-30 17:45 UTC, guyroyse commented on README.md
> +Except for the network, the client will not emmit any events any more.
The client will not emit any other events beyond those listed abovee.

2021-11-30 17:46 UTC, guyroyse commented on README.md
> +Except for the network, the client will not emmit any events any more.
Doh! I spelled above wrong. ;)

2021-12-02 01:14 UTC, AnnAngela commented
@guyroyse I'm sorry that I deleted the patch repository accidentally, so I have to open another pr #1753 to continue.

2021-12-02 01:14 UTC, closed without merging