Add zrevrange zrevrangewithscores
redis/node-redis pull request #2109
Opened 2022-04-26 18:18 UTC by simonprickett

Adds `ZREVRANGE` and `ZREVRANGEWITHSCORES` commands:

```javascript
const client = createClient();
await client.connect();

await client.zAdd('mysortedset', [
  {
    score: 99,
    value: 'Ninety Nine'
  },
  {
    score: 100,
    value: 'One Hundred'
  },
  {
    score: 101,
    value: 'One Hundred and One'
  }
]);

console.log('ZREVRANGE:');
console.log(await client.zRevRange('mysortedset', 0, -1));
  
console.log('ZREVRANGE WITHSCORES:');
console.log(await client.zRevRangeWithScores('mysortedset', 0, -1));
  
await client.quit();
```

output:

```
ZREVRANGE:
[ 'One Hundred and One', 'One Hundred', 'Ninety Nine' ]
ZREVRANGE WITHSCORES:
[
  { value: 'One Hundred and One', score: 101 },
  { value: 'One Hundred', score: 100 },
  { value: 'Ninety Nine', score: 99 }
]
```

Closes #2107 Closes #2173

2022-04-26 22:56 UTC, leibale requested changes

2022-04-26 22:56 UTC, leibale commented on packages/client/lib/commands/ZREVRANGE.spec.ts
> +    describe('transformArguments', () => {
```javascript
it('transformArguments', () => {
    assert.deepEqual(
        transformArguments('src', 0, 1),
        ['ZREVRANGE', 'src', '0', '1']
    );
});
```

2022-04-26 22:56 UTC, leibale commented on packages/client/lib/commands/ZREVRANGE.ts
> +    const args = [
```javascript
return [
    'ZREVRANGE',
    key,
    transformStringNumberInfinityArgument(min),
    transformStringNumberInfinityArgument(max)
];
```

2022-04-26 22:56 UTC, leibale commented on packages/client/lib/commands/ZREVRANGE_WITHSCORES.spec.ts
> +    describe('transformArguments', () => {
same here

2022-04-26 22:56 UTC, leibale commented on packages/client/lib/commands/ZREVRANGE_WITHSCORES.ts
> +    const args = [
same here

2022-10-31 12:41 UTC, closed without merging

2022-10-31 14:46 UTC, simonprickett commented
@leibale looks like I deleted my fork and got a fresh copy and had forgotten about this PR :(