#2287 Add example scripts showing pub/sub usage.
redis/node-redis pull request #2288
Opened 2022-10-05 21:32 UTC by con-mark

### Description

Added example requested for Issue #2287 

created pubsub-publisher.js and pubsub-subscriber.js

---

### Checklist

- [ ] Does `npm test` pass with this change (including linting)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

2022-10-06 09:40 UTC, SuzeShardlow commented
Closes #2287 when approved and merged.

2022-10-06 18:09 UTC, SuzeShardlow commented
@con-mark thanks for your PR - not sure if you have seen @simonprickett's comments above, but he is asking for a couple of changes before we merge this.  Thanks!

2022-10-06 21:22 UTC, con-mark commented
Hi @simonprickett  @SuzeShardlow  I have made requested changes please let me know if any further changes are needed.

2022-10-06 22:17 UTC, SuzeShardlow commented
Thanks @con-mark, we will take a look in our morning! :)

2022-10-07 16:17 UTC, simonprickett requested changes
I've left some tidy up commit suggestions, but am also unable to get the example to work, the publisher publishes messages but the subscriber never outputs anything...

2022-10-07 16:17 UTC, simonprickett commented on examples/pubsub-publisher.js
> +  console.log(`publising message on ${channel1}`);
```suggestion
  console.log(`publishing message on ${channel1}`);

```

2022-10-07 16:17 UTC, simonprickett commented on examples/pubsub-publisher.js
> +  console.log(`publising message on ${channel2}`);
```suggestion
  console.log(`publishing message on ${channel2}`);

```

2022-10-07 16:17 UTC, simonprickett commented on examples/pubsub-publisher.js
> +//declare constant variables for the name of the clients we will publish to as they will be required for logging
```suggestion
// Declare constant variables for the name of the clients we will publish to as they will be required for logging.

```

2022-10-07 16:17 UTC, simonprickett commented on examples/pubsub-publisher.js
> +  //1st channel created to publish 10000 messages
```suggestion
  // 1st channel created to publish 10000 messages.
```

2022-10-07 16:17 UTC, simonprickett commented on examples/pubsub-publisher.js
> +  //2nd channel created to publish 10000 messages
```suggestion
  // 2nd channel created to publish 10000 messages.
```

2022-10-07 16:17 UTC, simonprickett commented on examples/pubsub-subscriber.js
> +//create and connect client before doing any redis commands
```suggestion
// create and connect client before executing any Redis commands.
```

2022-10-07 16:17 UTC, simonprickett commented on examples/pubsub-subscriber.js
> +//Each subscriber needs to connect individually therefore we duplicate the client.
```suggestion
// Each subscriber needs to connect individually therefore we duplicate the client.
```

2022-10-07 16:17 UTC, simonprickett commented on examples/pubsub-subscriber.js
> +//This subscriber only will receive messages from channel 1 as they are using the subscribe method and subscribed to chan1nel
```suggestion
// This subscriber only will receive messages from channel 1 as they are using the subscribe method and subscribed to chan1nel.

```

2022-10-07 16:17 UTC, simonprickett commented on examples/pubsub-subscriber.js
> +//This subscriber only will receive messages from channel 2 as they are using the subscribe method and subscribed to chan2nel
```suggestion
// This subscriber only will receive messages from channel 2 as they are using the subscribe method and subscribed to chan2nel.
```

2022-10-07 16:17 UTC, simonprickett commented on examples/pubsub-subscriber.js
> +//This subscriber receive messages from both channel 1 and channel 2 thanks the pSubscribe method.
```suggestion
// This subscriber receive messages from both channel 1 and channel 2 using the pSubscribe method.
```

2022-10-07 16:17 UTC, simonprickett commented on examples/pubsub-subscriber.js
> +//clean up after ourselves by unsubsribing
```suggestion
// Clean up after ourselves by unsubscribing.

```

2022-10-07 21:08 UTC, SuzeShardlow commented
@con-mark, please see the above comments from @simonprickett and let us know if you can make the changes - the subscriber in your example isn't outputting anything for us.  Thanks!

2022-10-08 17:16 UTC, con-mark commented
Hi @SuzeShardlow  and @simonprickett  I have made the tidy up comments and I have fixed the issue with the subscriber seems like doing the clean up and closing the client before they got a chance to interact with the Redis to publish or subscribe.

Please let me know if you need anything more.

I also may suggest some other improvement for your hacktoberfest contribution might be for someone to create a docker compose that will allow the the running of the examples with a redis image for people to not have to worry for set up :)

2022-10-10 19:07 UTC, con-mark commented on examples/pubsub-subscriber.js
> +//clean up after ourselves by unsubsribing
removed clean up

2022-10-10 19:07 UTC, con-mark commented on examples/pubsub-subscriber.js
> +//This subscriber receive messages from both channel 1 and channel 2 thanks the pSubscribe method.
done

2022-10-10 19:07 UTC, con-mark commented on examples/pubsub-subscriber.js
> +//This subscriber only will receive messages from channel 2 as they are using the subscribe method and subscribed to chan2nel
done

2022-10-10 19:07 UTC, con-mark commented on examples/pubsub-subscriber.js
> +//This subscriber only will receive messages from channel 1 as they are using the subscribe method and subscribed to chan1nel
done

2022-10-10 19:08 UTC, con-mark commented on examples/pubsub-subscriber.js
> +//Each subscriber needs to connect individually therefore we duplicate the client.
done

2022-10-10 19:08 UTC, con-mark commented on examples/pubsub-publisher.js
> +  //2nd channel created to publish 10000 messages
done

2022-10-10 19:08 UTC, con-mark commented on examples/pubsub-publisher.js
> +  //1st channel created to publish 10000 messages
done

2022-10-10 19:08 UTC, con-mark commented on examples/pubsub-publisher.js
> +//declare constant variables for the name of the clients we will publish to as they will be required for logging
done

2022-10-10 19:08 UTC, con-mark commented on examples/pubsub-publisher.js
> +  console.log(`publising message on ${channel2}`);
done

2022-10-10 19:08 UTC, con-mark commented on examples/pubsub-publisher.js
> +  console.log(`publising message on ${channel1}`);
done

2022-10-11 13:22 UTC, simonprickett requested changes
@con-mark thanks - left one tiny suggestion and this should then be good to go.

2022-10-11 13:22 UTC, simonprickett commented on examples/pubsub-subscriber.js
> +//This subscriber not receive any messages cause its channel does not exist
```suggestion
// This subscriber will not receive any messages as its channel does not exist.
```

2022-10-13 19:51 UTC, con-mark commented
Hi @SuzeShardlow  @simonprickett  is any further changes needed here? Please let me know :)

2022-10-14 21:50 UTC, simonprickett approved these changes

2022-10-14 22:07 UTC, merged

2022-10-14 22:08 UTC, SuzeShardlow commented
@con-mark thanks for your contribution!  If you are a member of our Discord server, please let us know your handle so we can give you the `Hacktoberfest 2022` role.  Thanks!

2022-10-16 14:25 UTC, con-mark commented
Hi @SuzeShardlow my discord is dev-mark#1608

2022-10-16 15:16 UTC, SuzeShardlow commented
Thanks @con-mark, I've given you the role in Discord :)