#2285-Add-example-scripts-hyperloglog - Added hyperloglog examples to…
redis/node-redis pull request #2289
Opened 2022-10-10 19:59 UTC by ade1705

Added example scripts for the hyperloglog as requested - #2285 

created a hyperloglog.js file

### Checklist

- [ ] Does `npm test` pass with this change (including linting)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

2022-10-10 20:52 UTC, SuzeShardlow commented
Closes #2285 when merged.

2022-10-11 13:55 UTC, simonprickett requested changes
Thank you - looking good, the code works well thanks.  I've left a couple of suggestions, please ensure all comments have a space between the `//` and the text, and that sentences end with a full stop / period... so:

```
// this is a comment.
```

rather than:

```
//this is a comment
```

Thank you!

2022-10-11 13:55 UTC, simonprickett commented on examples/hyperloglog.js
> +//Log license plates of each car scanned at each intersection and add to the intersections Hyperloglog
```suggestion
// Log license plates of each car scanned at each intersection and add to the intersections Hyperloglog.
```

2022-10-11 14:34 UTC, ade1705 commented
@simonprickett Thanks for the feedback, Changes made

2022-10-12 07:35 UTC, SuzeShardlow commented
Thanks @ade1705, we'll review this!  In the meantime, if you're a member of our Discord server (https://discord.gg/redis), please let us know your handle.  Thanks!

2022-10-12 15:50 UTC, ade1705 commented
> Thanks @ade1705, we'll review this! In the meantime, if you're a member of our Discord server (https://discord.gg/redis), please let us know your handle. Thanks!

Yea, I am a member of the discord, my handle `@TrussDamola`

2022-10-14 19:33 UTC, SuzeShardlow commented
Closes #2285.  Thanks @ade1705!  I'll give you the `Hacktoberfest 2022` role on Discord :)

2022-10-14 19:34 UTC, merged