fix #2364 - fix FT.SEARCH RETURN []
redis/node-redis pull request #2366
Opened 2023-01-04 21:53 UTC by leibale

fix #2364 - fix FT.SEARCH RETURN []

2023-01-04 21:59 UTC, guyroyse requested changes
LGTM except for the stray console.log.

2023-01-04 21:59 UTC, guyroyse commented on packages/search/lib/commands/SEARCH.ts
> +    console.log(reply);
Probably want to remove this.

2023-01-04 22:37 UTC, guyroyse approved these changes

2023-01-04 22:38 UTC, guyroyse approved these changes
LGTM

2023-01-11 15:35 UTC, TheArmagan commented
Please approve that pull request its needed.

2023-01-11 15:51 UTC, TheArmagan approved these changes
everything looks ok to me

2023-01-11 19:54 UTC, leibale commented
This will get released once #2373  is ready

2023-01-18 17:54 UTC, merged