Support JSON.MERGE Command
redis/node-redis pull request #2511
Opened 2023-05-16 13:13 UTC by shacharPash

### Description

> Describe your pull request here

---

### Checklist

- [ ] Does `npm test` pass with this change (including linting)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

Closes #2500

2023-05-18 08:10 UTC, leibale requested changes

2023-05-18 08:10 UTC, leibale commented on packages/json/lib/commands/MERGE.spec.ts
> +});
empty line please.. :)

2023-05-18 08:10 UTC, leibale commented on packages/json/lib/commands/MERGE.ts
> +export declare function transformReply(): 'OK' | null;
`null`?! + empty line..

2023-05-21 09:26 UTC, leibale approved these changes

2023-07-19 09:06 UTC, kiyaGu commented
Hi @shacharPash @leibale, do you know when this feature is going to be available?

2023-07-19 18:19 UTC, leibale commented
@kiyaGu we're waiting for RedisJSON 2.6 to be released, see [here](https://github.com/RedisJSON/RedisJSON/releases)

2023-08-30 13:51 UTC, arsengoian commented
@leibale looks like it has been released several weeks ago

2023-09-07 16:40 UTC, znycheporuk commented
Any updates?

> @kiyaGu we are waiting for RedisJSON 2.6 to be released, see [here](https://github.com/RedisJSON/RedisJSON/releases)

2023-09-18 21:54 UTC, merged