Add support for LATENCY LATEST. #1957
redis/node-redis pull request #2514
Opened 2023-05-18 09:54 UTC by Karnav123

### Description

Checklist
 Does npm test pass with this change (including linting)?
 Is the new or changed code fully tested?
 Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
Fix for https://github.com/redis/node-redis/issues/1957
> Describe your pull request here

---

### Checklist

- [ ] Does `npm test` pass with this change (including linting)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

2023-05-19 04:45 UTC, Karnav123 commented
> ## [Codecov](https://app.codecov.io/gh/redis/node-redis/pull/2514?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=redis) Report
> Patch coverage: **`100.00`**% and project coverage change: **`-0.16`** :warning:
> > Comparison is base [(`67d9c3c`)](https://app.codecov.io/gh/redis/node-redis/commit/67d9c3c46a6112fbb8b878c8708966433ad0ed45?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=redis) 95.67% compared to head [(`14741bf`)](https://app.codecov.io/gh/redis/node-redis/pull/2514?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=redis) 95.52%.
> 
> > :exclamation: Current head 14741bf differs from pull request most recent head 26ad2ed. Consider uploading reports for the commit 26ad2ed to get more accurate results
> 
> :exclamation: Your organization is not using the GitHub App Integration. As a result you may experience degraded service beginning May 15th. Please [install the Github App Integration](https://github.com/apps/codecov) for your organization. [Read more](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=redis).
> 
> <details><summary>Additional details and impacted files</summary>
> 
> 
> ```diff
> @@            Coverage Diff             @@
> ##           master    #2514      +/-   ##
> ==========================================
> - Coverage   95.67%   95.52%   -0.16%     
> ==========================================
>   Files         455      456       +1     
>   Lines        4552     4555       +3     
>   Branches      522      522              
> ==========================================
> - Hits         4355     4351       -4     
> - Misses        128      133       +5     
> - Partials       69       71       +2     
> ```
> 
> 
> | [Impacted Files](https://app.codecov.io/gh/redis/node-redis/pull/2514?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=redis) | Coverage Δ | |
> |---|---|---|
> | [packages/client/lib/client/commands.ts](https://app.codecov.io/gh/redis/node-redis/pull/2514?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=redis#diff-cGFja2FnZXMvY2xpZW50L2xpYi9jbGllbnQvY29tbWFuZHMudHM=) | `100.00% <100.00%> (ø)` | |
> | [packages/client/lib/commands/LATENCY\_LATEST.ts](https://app.codecov.io/gh/redis/node-redis/pull/2514?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=redis#diff-cGFja2FnZXMvY2xpZW50L2xpYi9jb21tYW5kcy9MQVRFTkNZX0xBVEVTVC50cw==) | `100.00% <100.00%> (ø)` | |
> 
> ... and [2 files with indirect coverage changes](https://app.codecov.io/gh/redis/node-redis/pull/2514/indirect-changes?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=redis)
> 
> 
> </details>
> 
> [:umbrella: View full report in Codecov by Sentry](https://app.codecov.io/gh/redis/node-redis/pull/2514?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=redis).   
> :loudspeaker: Do you have feedback about the report comment? [Let us know in this issue](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=redis).
> 

My changes are not there in the mentioned files. However, please help me fix the issue. This is my first pull request on this repo.

2023-05-19 17:23 UTC, Karnav123 commented
@leibale could you please take some time to review this pull request. This is my first PR. Please guide me in case I have missed something.

2023-05-19 17:25 UTC, leibale commented
@Karnav123 tanks for contributing! I will next week.. :)

2023-05-21 09:24 UTC, leibale requested changes

2023-05-21 09:24 UTC, leibale commented on packages/client/lib/commands/LATENCY_LATEST.spec.ts
> +        assert.strictEqual(latencyType, true);
use 
```javascript
await Promise.all([
  client.configSet('latency-monitor-threshold', '100'),
  client.sendCommand(['DEBUG', 'SLEEP', '1'])
]);
```

to generate "latency event", then extend the test to test the events:

```javascript
assert.ok(Array.isArray(latency));
for (const event of latency) {
  // assert event properties
}
```

2023-05-21 09:24 UTC, leibale commented on packages/client/lib/commands/LATENCY_LATEST.ts
> +export declare function transformReply(): Array<latenctStats>;
The reply type is 
```javascript
Array<[
  name: string,
  timestamp: number,
  latestLatency: number,
  allTimeLatency: number
]>
```

2023-05-21 17:11 UTC, Karnav123 commented
> @Karnav123 thanks for contributing! I will next week.. :)

I have implemented your review comments. Please, take a look whenever you have time.

2023-05-24 10:25 UTC, leibale commented on packages/client/lib/commands/LATENCY_LATEST.spec.ts
> +        for (const event of latency) {
```suggestion
        for (const [name, timestamp, latestLatency, allTimeLatency] of latency) {
            assert.equal(typeof name, 'string');
            assert.equal(typeof timestamp, 'number');
            assert.equal(typeof latestLatency, 'number');
            assert.equal(typeof allTimeLatency, 'number');
        }
```

2023-05-24 10:27 UTC, leibale commented on packages/client/lib/commands/LATENCY_LATEST.spec.ts
> +        }
```suggestion
        for (const [name, timestamp, latestLatency, allTimeLatency] of latency) {
            assert.equal(typeof name, 'string');
            assert.equal(typeof timestamp, 'number');
            assert.equal(typeof latestLatency, 'number');
            assert.equal(typeof allTimeLatency, 'number');
        }
```

2023-05-29 12:59 UTC, leibale approved these changes

2023-05-29 13:00 UTC, merged